/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as DatentransparenzRouteImport } from './routes/datentransparenz'
import { Route as KompetenzRouteImport } from './routes/kompetenz'
import { Route as WillkommenRouteImport } from './routes/willkommen'
import { Route as TrainingScenarioIdRouteImport } from './routes/training.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const DatentransparenzRoute = DatentransparenzRouteImport.update({
  id: '/datentransparenz',
  path: '/datentransparenz',
  getParentRoute: () => rootRouteImport,
} as any)
const KompetenzRoute = KompetenzRouteImport.update({
  id: '/kompetenz',
  path: '/kompetenz',
  getParentRoute: () => rootRouteImport,
} as any)
const WillkommenRoute = WillkommenRouteImport.update({
  id: '/willkommen',
  path: '/willkommen',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingScenarioIdRoute = TrainingScenarioIdRouteImport.update({
  id: '/training/$scenarioId',
  path: '/training/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/datentransparenz': typeof DatentransparenzRoute
  '/kompetenz': typeof KompetenzRoute
  '/willkommen': typeof WillkommenRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/datentransparenz': typeof DatentransparenzRoute
  '/kompetenz': typeof KompetenzRoute
  '/willkommen': typeof WillkommenRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/datentransparenz': typeof DatentransparenzRoute
  '/kompetenz': typeof KompetenzRoute
  '/willkommen': typeof WillkommenRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/datentransparenz'
    | '/kompetenz'
    | '/willkommen'
    | '/training/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/datentransparenz'
    | '/kompetenz'
    | '/willkommen'
    | '/training/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/anmelden'
    | '/datentransparenz'
    | '/kompetenz'
    | '/willkommen'
    | '/training/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnmeldenRoute: typeof AnmeldenRoute
  DatentransparenzRoute: typeof DatentransparenzRoute
  KompetenzRoute: typeof KompetenzRoute
  WillkommenRoute: typeof WillkommenRoute
  TrainingScenarioIdRoute: typeof TrainingScenarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datentransparenz': {
      id: '/datentransparenz'
      path: '/datentransparenz'
      fullPath: '/datentransparenz'
      preLoaderRoute: typeof DatentransparenzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kompetenz': {
      id: '/kompetenz'
      path: '/kompetenz'
      fullPath: '/kompetenz'
      preLoaderRoute: typeof KompetenzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/willkommen': {
      id: '/willkommen'
      path: '/willkommen'
      fullPath: '/willkommen'
      preLoaderRoute: typeof WillkommenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$scenarioId': {
      id: '/training/$scenarioId'
      path: '/training/$scenarioId'
      fullPath: '/training/$scenarioId'
      preLoaderRoute: typeof TrainingScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnmeldenRoute: AnmeldenRoute,
  DatentransparenzRoute: DatentransparenzRoute,
  KompetenzRoute: KompetenzRoute,
  WillkommenRoute: WillkommenRoute,
  TrainingScenarioIdRoute: TrainingScenarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
