/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingScenarioIdRouteImport } from './routes/training.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingScenarioIdRoute = TrainingScenarioIdRouteImport.update({
  id: '/training/$scenarioId',
  path: '/training/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/training/$scenarioId': typeof TrainingScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/training/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/training/$scenarioId'
  id: '__root__' | '/' | '/training/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainingScenarioIdRoute: typeof TrainingScenarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$scenarioId': {
      id: '/training/$scenarioId'
      path: '/training/$scenarioId'
      fullPath: '/training/$scenarioId'
      preLoaderRoute: typeof TrainingScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainingScenarioIdRoute: TrainingScenarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
